name: Security Vulnerability
description: Report a security vulnerability or exploit in the project
title: "[SECURITY] "
labels: security
assignees: ''

body:
  - type: markdown
    attributes:
      value: >
        ⚠️ **Important:** Do NOT include full exploit code if it could be used maliciously. 
        Provide enough detail for us to understand the issue safely.

  - type: input
    id: summary
    attributes:
      label: Summary
      description: Briefly describe the vulnerability
      placeholder: Example: SQL Injection in login endpoint
      required: true

  - type: textarea
    id: steps_to_reproduce
    attributes:
      label: Steps to Reproduce
      description: Step-by-step instructions to reproduce the vulnerability
      required: true

  - type: textarea
    id: impact
    attributes:
      label: Potential Impact
      description: Describe what an attacker could do if this vulnerability is exploited
      required: true

  - type: textarea
    id: suggested_fix
    attributes:
      label: Suggested Fix
      description: Optional suggestion on how to fix it
      required: false

  - type: input
    id: contact
    attributes:
      label: Contact Email
      description: Provide an email so we can follow up with you if needed
      required: true
