name: Build project

on:
  push:
    tags:
      - 'v*.*.*' # e.g. v0.1.0
  workflow_dispatch:
    inputs:
      version:
        description: 'Version name (e.g. v0.1.0)'
        required: true
        default: 'v0.1.0'

# 👇 Needed so GITHUB_TOKEN can publish releases
permissions:
  contents: write

jobs:
  buildForAllSupportedPlatforms:
    name: Build for ${{ matrix.targetPlatform }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        targetPlatform:
          - StandaloneWindows64

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          lfs: true

      - uses: actions/cache@v3
        with:
          path: Library
          key: Library-${{ matrix.targetPlatform }}
          restore-keys: Library-

      - if: matrix.targetPlatform == 'Android'
        uses: jlumbroso/free-disk-space@v1.3.1

      - uses: game-ci/unity-builder@v4
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          targetPlatform: ${{ matrix.targetPlatform }}

      - uses: actions/upload-artifact@v4
        with:
          name: Build-${{ matrix.targetPlatform }}
          path: build/${{ matrix.targetPlatform }}

      # Define version for release (tag if push, input if manual)
      - name: Set version
        id: version
        run: |
          if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
            echo "version=${{ github.event.inputs.version }}" >> $GITHUB_OUTPUT
          else
            echo "version=${{ github.ref_name }}" >> $GITHUB_OUTPUT
          fi

      # Create GitHub Release
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.version.outputs.version }}
          name: NecroStrike-${{ steps.version.outputs.version }}
          files: build/${{ matrix.targetPlatform }}/**
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Upload to itch.io
      - name: Upload to itch.io
        uses: manleydev/butler-publish-itchio-action@master
        with:
          butlerApiKey: ${{ secrets.BUTLER_API_KEY }}
          gameData: build/${{ matrix.targetPlatform }}
          itchUsername: theoscreation
          itchGameId: zombie-game
          channel: windows
